name: PR CI Single Run
on: workflow_dispatch
jobs:
  build-test:
    runs-on: ubuntu-latest  # This is ignored by act, but kept for GitHub Actions compatibility
    container: public.ecr.aws/amazonlinux/amazonlinux:2023
    name: build-test-job
    steps:
      - run: |
          yum -y update && yum -y install git tar util-linux findutils yum-utils
      - uses: actions/checkout@v3
      
      - name: Fetch and Install EFA Installer Dependencies
        run: |
          curl -O https://efa-installer.amazonaws.com/aws-efa-installer-latest.tar.gz
          tar -xf aws-efa-installer-*.tar.gz
          cd aws-efa-installer/RPMS/ALINUX2023/x86_64
          find . | grep rpm$ | xargs yum -y localinstall

      - name: Install hwloc, utilities
        run: |
          yum -y install hwloc-devel autoconf automake libtool gcc gcc-c++ git make

      - name: Install CUDA
        run: |
          dnf config-manager --add-repo \
             http://developer.download.nvidia.com/compute/cuda/repos/amzn2023/x86_64/cuda-amzn2023.repo \
             --save
          yum -y clean expire-cache
          yum -y install cuda-cudart-devel-12-6 cuda-crt-12-6

      - name: Call `autoreconf -ivf`
        run: |
          ./autogen.sh

      - name: Run Configure
        run: |
          ./configure --with-mpi=/opt/amazon/openmpi \
                     --with-libfabric=/opt/amazon/efa \
                     --enable-tests=yes \
                     --enable-werror=yes \
                     --enable-picky-compiler=yes \
                     --enable-platform-aws \
                     --with-cuda=/usr/local/cuda/

      - name: Call `make`
        run: make V=1

      - name: Call `make check`
        run: make check V=1 || (cat tests/unit/test-suite.log && exit 1)

      - name: Call `make install`
        run: make install V=1

      - name: Call `make distcheck`
        run: make distcheck V=1
